[project]
name = "emotion-playlist-mcp"
version = "0.1.0"
description = "An MCP Server that creates playlists tailored to your emotions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
